# Generated by Django 5.0.7 on 2024-08-10 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_remove_about_homepage_homepage_about_us'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='about_us',
        ),
        migrations.DeleteModel(
            name='About',
        ),
    ]
