# Generated by Django 5.0.7 on 2024-08-11 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_alter_about_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='homepage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_us', to='homepage.homepage'),
        ),
    ]
