# Generated by Django 5.0.7 on 2024-08-11 15:23

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_alter_about_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('review', ckeditor.fields.RichTextField()),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='homepage.homepage')),
            ],
        ),
    ]
