# Generated by Django 5.0.7 on 2024-08-11 18:54

import homepage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.FloatField(default=4.5, validators=[homepage.models.validate_allowed_rating_value]),
            preserve_default=False,
        ),
    ]
