# Generated by Django 5.0.7 on 2024-08-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_name',
            field=models.CharField(choices=[('Email', 'Email'), ('Phone', 'Phone'), ('Instagram', 'Instagram'), ('Facebook', 'Facebook')], max_length=100, unique=True),
        ),
    ]
