# Generated by Django 5.0.7 on 2024-08-12 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0015_alter_contact_contact_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='homepage/banner_images/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner_images', to='homepage.homepage')),
            ],
        ),
    ]
