# Generated by Django 5.0.7 on 2024-08-13 18:14

import ckeditor.fields
import homepage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0018_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review',
            field=ckeditor.fields.RichTextField(validators=[homepage.models.validate_review_length]),
        ),
    ]
