# Generated by Django 5.0.7 on 2024-08-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0019_alter_review_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_name',
            field=models.CharField(choices=[('Email', 'Email'), ('Phone', 'Phone'), ('Instagram', 'Instagram'), ('Facebook', 'Facebook'), ('Whatsapp', 'Whatsapp')], max_length=100, unique=True),
        ),
    ]
