# Generated by Django 5.0.7 on 2024-08-21 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0020_alter_contact_contact_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='caption',
        ),
    ]
