# Generated by Django 5.0.7 on 2024-08-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0021_remove_galleryimage_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerimage',
            name='caption',
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
