# Generated by Django 5.0.7 on 2024-07-22 13:27

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Policies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('why_us', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('cancellation_policy', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('terms_and_conditions', ckeditor.fields.RichTextField()),
                ('otherImportantThingsToRemember', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('banner_image', models.ImageField(upload_to='banners/')),
                ('overview', ckeditor.fields.RichTextField()),
                ('duration', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('inquiry_form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trips.inquirycontact')),
                ('policy_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trip', to='trips.policies')),
            ],
        ),
        migrations.CreateModel(
            name='PickupDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_point', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('arrival_timing', models.CharField(max_length=10)),
                ('departure_timing', models.CharField(max_length=10)),
                ('quad_sharing_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('triple_sharing_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('double_sharing_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('single_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('per_person_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('some_notes', models.TextField(blank=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickupDetails', to='trips.trip')),
            ],
        ),
        migrations.CreateModel(
            name='MustKnow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inclusions', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('exclusions', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('thingsToCarry', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('otherImportantThingsToRemember', models.TextField(blank=True, max_length=500)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mustKnow', to='trips.trip')),
            ],
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, max_length=200)),
                ('details', ckeditor.fields.RichTextField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='trips.trip')),
            ],
        ),
    ]
