# Generated by Django 5.0.7 on 2024-07-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_type_of_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='type_of_group',
            field=models.CharField(max_length=20),
        ),
    ]
