# Generated by Django 5.0.7 on 2024-07-24 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_alter_trip_type_of_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mustknow',
            name='otherImportantThingsToRemember',
        ),
        migrations.RemoveField(
            model_name='pickupdetails',
            name='some_notes',
        ),
        migrations.RemoveField(
            model_name='policies',
            name='otherImportantThingsToRemember',
        ),
    ]
