# Generated by Django 5.0.7 on 2024-08-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_trip_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='pdf',
            field=models.FileField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
