# Generated by Django 5.0.7 on 2024-08-08 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_remove_pickupdetails_per_person_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='inquiry_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='trips.inquirycontact'),
        ),
    ]
