# Generated by Django 5.0.7 on 2024-08-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0012_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.AlterField(
            model_name='trip',
            name='banner_image',
            field=models.ImageField(upload_to='trips/banners/'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='trips/uploads/', verbose_name='PDF'),
        ),
    ]
