# Generated by Django 5.0.7 on 2024-08-10 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0013_delete_about_alter_trip_banner_image_alter_trip_pdf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policies',
            options={'verbose_name': 'Policies', 'verbose_name_plural': 'Policies'},
        ),
    ]
