# Generated by Django 5.0.7 on 2024-08-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0014_alter_policies_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
