# Generated by Django 5.0.7 on 2024-08-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0016_trip_starting_from_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='starting_from_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
